<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <NoWarn>$(NoWarn);NU1701;NU1902;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Interop.Microsoft.Office.Interop.Publisher" Version="2.2.0" />
    <PackageReference Include="OpenMcdf" Version="2.3.1" />
    <PackageReference Include="MSOfficeCore.Interop" Version="15.0.2" />
  </ItemGroup>

</Project>
