<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PublisherConverter.TestWorker</RootNamespace>
    <AssemblyName>PublisherConverter.TestWorker</AssemblyName>
    <NoWarn>$(NoWarn);NU1701;NU1902;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PublisherConverter.Core\PublisherConverter.Core.csproj" />
  </ItemGroup>

</Project>
